#  _    _ _   _ _    _____      _   _   _                 
# | |  | | | (_) |  / ____|    | | | | (_)                
# | |  | | |_ _| | | (___   ___| |_| |_ _ _ __   __ _ ___ 
# | |  | | __| | |  \___ \ / _ \ __| __| | '_ \ / _` / __|
# | |__| | |_| | |  ____) |  __/ |_| |_| | | | | (_| \__ \
#  \____/ \__|_|_| |_____/ \___|\__|\__|_|_| |_|\__, |___/
#                                                __/ |    
#                                               |___/     
#

Date: "dd/MM/yyyy"

Format: "0.00"

DataMode: "Local"
SaveDataIn: "plugins/GreenJobs/data/"