main: code.warsteiner.jobs.GreenJobs
version: 1.2.5
name: GreenJobs
author: Warsteiner37
api-version: 1.16
depend: [Vault]
softdepend: [WorldGuard, WorldEdit, PlaceholderAPI, MythicMobs, ItemsAdder, NoteBlockAPI]
description: Let Players work!
website: https://warsteiner37.eu/

commands:
  jobsadmin:
  jobs:
    aliases: [job, work]